parameters:
- name: terraformDestroy
  displayName: Terraform Destroy all resources?
  type: boolean
  default: false
- name: runTerraformCustomCommand
  displayName: Run Terraform Custom Command Stage?
  type: boolean
  default: false
- name: terraformCustomCommand
  displayName: Terraform Custom Command (state)
  type: string
  default: "REQUIRED_DEFAULT_VALUE"
- name: terraformCustomCommandOptions
  displayName: Terraform Custom Command Options (rm resource.id)
  type: string
  default: "REQUIRED_DEFAULT_VALUE"

trigger:
  # https://learn.microsoft.com/en-us/azure/devops/pipelines/repos/azure-repos-git?view=azure-devops&tabs=yaml#batching-ci-runs
  batch: true

resources:
  repositories:
    - repository: templates
      type: git
      name: Shared/PipelineTemplates
      ref: bugfix/fix-reference-to-plan-file
      # TODO: reference tag
      # ref: refs/tags/v1.0.0

pool:
  vmImage: ubuntu-22.04

variables:
  - name: tfstate.ResourceGroup
    value: AzureVirtualDesktops
  - name: tfstate.StorageAccount
    value: tfsavdaue80o4y
  - name: tfState.Container
    value: infrastructure
  - name: tfState.KeyPrefix
    value: nerdio

stages:
  - stage: Shared
    displayName: Shared
    variables:
      tfState.Key: $(parameters.tfState.KeyPrefix)/shr/terraform.tfstate
      varfile: _vars/shr.tfvars
    jobs:
      - ${{ if eq(variables['Build.Reason'], 'PullRequest') }}:
          - template: terraform/pr-validation.yml@templates
            parameters:
              serviceConnection: Azure Virtual Desktops - Non-Production
              serviceConnectionBackend: Azure Virtual Desktops - Non-Production
      - ${{ else }}:
          - template: terraform/create-plan.yml@templates
            parameters:
              serviceConnection: Azure Virtual Desktops - Non-Production
              serviceConnectionBackend: Azure Virtual Desktops - Non-Production
               # Terraform Plan Parameters
              ${{ if eq(parameters.terraformDestroy, true) }}:
                  planCommandOptions: -destroy
              # Terraform Custom Command Parameters
              runCustomCommand: ${{ parameters.runTerraformCustomCommand }}
              customCommand: ${{ parameters.terraformCustomCommand }}
              customCommandOptions: ${{ parameters.terraformCustomCommandOptions }}
          - template: terraform/deploy-plan.yml@templates
            parameters:
              serviceConnection: Azure Virtual Desktops - Non-Production
              serviceConnectionBackend: Azure Virtual Desktops - Non-Production
              deploymentEnvironment: Azure Virtual Desktops - Shared
        